name: Deploy Blogs
on:
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy_blogs]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup application
        uses: suXinjke/github-actions/build-node-application@master
        with:
          repository: suXinjke/suxin.space
      - name: Upload the application
        uses: suXinjke/github-actions/push-copy@master
        with:
          source-path: remote/dist/.
          target-path: target
          target-sub-path: .
          cleanup: false
          pre-push-run: |
            rm -rf target/404
            rm -rf target/assets
            rm -rf target/img
            rm -rf target/items
            rm -rf target/notes
            find target/. -maxdepth 1 -type f -delete